/* First, create our posts table: */
CREATE TABLE offers (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(50),
    body TEXT,
    email_creator VARCHAR(50),
    created DATETIME DEFAULT NULL,
    modified DATETIME DEFAULT NULL
);

/* Then insert some posts for testing: */
INSERT INTO offers (title, body, email_creator, created)
    VALUES ('Java Developer', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nihil obcaecati eaque unde possimus, veritatis culpa dolorem tenetur non natus exercitationem porro blanditiis cum laborum, ullam magnam ratione deleniti maxime atque.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nihil obcaecati eaque unde possimus, veritatis culpa dolorem tenetur non natus exercitationem porro blanditiis cum laborum, ullam magnam ratione deleniti maxime atque.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nihil obcaecati eaque unde possimus, veritatis culpa dolorem tenetur non natus exercitationem porro blanditiis cum laborum, ullam magnam ratione deleniti maxime atque.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nihil obcaecati eaque unde possimus, veritatis culpa dolorem tenetur non natus exercitationem porro blanditiis cum laborum, ullam magnam ratione deleniti maxime atque.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nihil obcaecati eaque unde possimus, veritatis culpa dolorem tenetur non natus exercitationem porro blanditiis cum laborum, ullam magnam ratione deleniti maxime atque.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nihil obcaecati eaque unde possimus, veritatis culpa dolorem tenetur non natus exercitationem porro blanditiis cum laborum, ullam magnam ratione deleniti maxime atque.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nihil obcaecati eaque unde possimus, veritatis culpa dolorem tenetur non natus exercitationem porro blanditiis cum laborum, ullam magnam ratione deleniti maxime atque.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nihil obcaecati eaque unde possimus, veritatis culpa dolorem tenetur non natus exercitationem porro blanditiis cum laborum, ullam magnam ratione deleniti maxime atque.', 'example@examples.com', NOW());
INSERT INTO offers (title, body, email_creator, created)
    VALUES ('Frontend Developer', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nihil obcaecati eaque unde possimus, veritatis culpa dolorem tenetur non natus exercitationem porro blanditiis cum laborum, ullam magnam ratione deleniti maxime atque.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nihil obcaecati eaque unde possimus, veritatis culpa dolorem tenetur non natus exercitationem porro blanditiis cum laborum, ullam magnam ratione deleniti maxime atque.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nihil obcaecati eaque unde possimus, veritatis culpa dolorem tenetur non natus exercitationem porro blanditiis cum laborum, ullam magnam ratione deleniti maxime atque.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nihil obcaecati eaque unde possimus, veritatis culpa dolorem tenetur non natus exercitationem porro blanditiis cum laborum, ullam magnam ratione deleniti maxime atque.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nihil obcaecati eaque unde possimus, veritatis culpa dolorem tenetur non natus exercitationem porro blanditiis cum laborum, ullam magnam ratione deleniti maxime atque.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nihil obcaecati eaque unde possimus, veritatis culpa dolorem tenetur non natus exercitationem porro blanditiis cum laborum, ullam magnam ratione deleniti maxime atque.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nihil obcaecati eaque unde possimus, veritatis culpa dolorem tenetur non natus exercitationem porro blanditiis cum laborum, ullam magnam ratione deleniti maxime atque.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nihil obcaecati eaque unde possimus, veritatis culpa dolorem tenetur non natus exercitationem porro blanditiis cum laborum, ullam magnam ratione deleniti maxime atque.', 'example@examples.com', NOW());
INSERT INTO offers (title, body, email_creator, created)
    VALUES ('Ruby backendDeveloper', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nihil obcaecati eaque unde possimus, veritatis culpa dolorem tenetur non natus exercitationem porro blanditiis cum laborum, ullam magnam ratione deleniti maxime atque.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nihil obcaecati eaque unde possimus, veritatis culpa dolorem tenetur non natus exercitationem porro blanditiis cum laborum, ullam magnam ratione deleniti maxime atque.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nihil obcaecati eaque unde possimus, veritatis culpa dolorem tenetur non natus exercitationem porro blanditiis cum laborum, ullam magnam ratione deleniti maxime atque.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nihil obcaecati eaque unde possimus, veritatis culpa dolorem tenetur non natus exercitationem porro blanditiis cum laborum, ullam magnam ratione deleniti maxime atque.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nihil obcaecati eaque unde possimus, veritatis culpa dolorem tenetur non natus exercitationem porro blanditiis cum laborum, ullam magnam ratione deleniti maxime atque.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nihil obcaecati eaque unde possimus, veritatis culpa dolorem tenetur non natus exercitationem porro blanditiis cum laborum, ullam magnam ratione deleniti maxime atque.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nihil obcaecati eaque unde possimus, veritatis culpa dolorem tenetur non natus exercitationem porro blanditiis cum laborum, ullam magnam ratione deleniti maxime atque.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nihil obcaecati eaque unde possimus, veritatis culpa dolorem tenetur non natus exercitationem porro blanditiis cum laborum, ullam magnam ratione deleniti maxime atque.', 'example@examples.com', NOW());
